#cloud-config
users:
  - name: newuser    # Replace 'newuser' with your desired username
    sudo: ['ALL=(ALL) NOPASSWD:ALL']  # Grants sudo privileges without a password prompt
    groups: sudo
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3Nza...    # Replace with the actual public SSH key from DigitalOcean's stored keys

package_update: true  # Update the package lists
package_upgrade: true  # Upgrade all packages

packages:
  - software-properties-common
  - wget
  - curl
  - mc
  - build-essential
  - file
  - git
  - git-core

runcmd:
  - wget https://raw.githubusercontent.com/hestiacp/hestiacp/release/install/hst-install.sh
  - chmod +x hst-install.sh
  
  # Create directory and run the setup script as the new user
  - sudo -u newuser mkdir -p /home/newuser/install
  - sudo -u newuser bash -c 'cd /home/newuser/install && curl -fsSL https://raw.githubusercontent.com/alchemizt/vps_setup_hestia/main/setup.sh -o setup.sh && chmod +x setup.sh && sudo bash ./setup.sh'
